[2025-04-22T00:55:25.472984+00:00] security.ERROR: Detected CSRF attack on /admin/element/unlock-elements {"request":"/admin/element/unlock-elements"} []
[2025-04-22T00:55:25.480336+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" at CsrfProtectionHandler.php line 60 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Detected CSRF Attack! Do not do evil things with pimcore ... ;-) at /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Security/CsrfProtectionHandler.php:60)"} []
[2025-04-22T01:06:29.938516+00:00] security.ERROR: Detected CSRF attack on /admin/class/save {"request":"/admin/class/save"} []
[2025-04-22T01:06:29.942986+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" at CsrfProtectionHandler.php line 60 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Detected CSRF Attack! Do not do evil things with pimcore ... ;-) at /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Security/CsrfProtectionHandler.php:60)"} []
[2025-04-22T01:06:35.069085+00:00] security.ERROR: Detected CSRF attack on /admin/element/unlock-elements {"request":"/admin/element/unlock-elements"} []
[2025-04-22T01:06:35.076262+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" at CsrfProtectionHandler.php line 60 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Detected CSRF Attack! Do not do evil things with pimcore ... ;-) at /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Security/CsrfProtectionHandler.php:60)"} []
[2025-04-22T01:26:59.877945+00:00] security.ERROR: Detected CSRF attack on /admin/element/unlock-elements {"request":"/admin/element/unlock-elements"} []
[2025-04-22T01:26:59.883617+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" at CsrfProtectionHandler.php line 60 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Detected CSRF Attack! Do not do evil things with pimcore ... ;-) at /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Security/CsrfProtectionHandler.php:60)"} []
[2025-04-22T01:27:11.187819+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "include/footer" (looked into: /var/www/html/templates) in "layout.html.twig" at line 133." at FilesystemLoader.php line 234 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Unable to find template \"include/footer\" (looked into: /var/www/html/templates) in \"layout.html.twig\" at line 133. at /var/www/html/vendor/twig/twig/src/Loader/FilesystemLoader.php:234)"} []
[2025-04-22T01:28:25.250269+00:00] security.ERROR: Detected CSRF attack on /admin/element/unlock-elements {"request":"/admin/element/unlock-elements"} []
[2025-04-22T01:28:25.257512+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" at CsrfProtectionHandler.php line 60 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Detected CSRF Attack! Do not do evil things with pimcore ... ;-) at /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Security/CsrfProtectionHandler.php:60)"} []
[2025-04-22T01:51:29.174767+00:00] security.ERROR: Detected CSRF attack on /admin/page/remove-from-session {"request":"/admin/page/remove-from-session"} []
[2025-04-22T01:51:29.179019+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" at CsrfProtectionHandler.php line 60 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Detected CSRF Attack! Do not do evil things with pimcore ... ;-) at /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Security/CsrfProtectionHandler.php:60)"} []
[2025-04-22T01:51:29.185426+00:00] security.ERROR: Detected CSRF attack on /admin/element/unlock-element {"request":"/admin/element/unlock-element"} []
[2025-04-22T01:51:29.189705+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" at CsrfProtectionHandler.php line 60 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Detected CSRF Attack! Do not do evil things with pimcore ... ;-) at /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Security/CsrfProtectionHandler.php:60)"} []
[2025-04-22T01:51:31.499070+00:00] security.ERROR: Detected CSRF attack on /admin/element/unlock-elements {"request":"/admin/element/unlock-elements"} []
[2025-04-22T01:51:31.503409+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" at CsrfProtectionHandler.php line 60 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Detected CSRF Attack! Do not do evil things with pimcore ... ;-) at /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Security/CsrfProtectionHandler.php:60)"} []
[2025-04-22T02:17:44.124786+00:00] security.ERROR: Detected CSRF attack on /admin/element/unlock-elements {"request":"/admin/element/unlock-elements"} []
[2025-04-22T02:17:44.127285+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" at CsrfProtectionHandler.php line 60 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Detected CSRF Attack! Do not do evil things with pimcore ... ;-) at /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Security/CsrfProtectionHandler.php:60)"} []
[2025-04-22T02:32:19.675649+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\SyntaxError: "Unknown "app_nav_data_links" function." at layout.html.twig line 96 {"exception":"[object] (Twig\\Error\\SyntaxError(code: 0): Unknown \"app_nav_data_links\" function. at /var/www/html/templates/layout.html.twig:96)"} []
[2025-04-22T02:38:36.081966+00:00] security.ERROR: Detected CSRF attack on /admin/element/unlock-elements {"request":"/admin/element/unlock-elements"} []
[2025-04-22T02:38:36.084648+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" at CsrfProtectionHandler.php line 60 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Detected CSRF Attack! Do not do evil things with pimcore ... ;-) at /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Security/CsrfProtectionHandler.php:60)"} []
[2025-04-22T02:38:48.930055+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\SyntaxError: "Unknown "app_navigation_data_links" function." at layout.html.twig line 96 {"exception":"[object] (Twig\\Error\\SyntaxError(code: 0): Unknown \"app_navigation_data_links\" function. at /var/www/html/templates/layout.html.twig:96)"} []
[2025-04-22T02:40:35.280522+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\SyntaxError: "Unknown "app_navigation_data_links" function." at layout.html.twig line 96 {"exception":"[object] (Twig\\Error\\SyntaxError(code: 0): Unknown \"app_navigation_data_links\" function. at /var/www/html/templates/layout.html.twig:96)"} []
[2025-04-22T02:44:38.642569+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\SyntaxError: "Unknown "endapply" tag." at layout.html.twig line 112 {"exception":"[object] (Twig\\Error\\SyntaxError(code: 0): Unknown \"endapply\" tag. at /var/www/html/templates/layout.html.twig:112)"} []
[2025-04-22T02:45:39.500752+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\SyntaxError: "Unknown "app_navigation_data_links" function." at layout.html.twig line 143 {"exception":"[object] (Twig\\Error\\SyntaxError(code: 0): Unknown \"app_navigation_data_links\" function. at /var/www/html/templates/layout.html.twig:143)"} []
[2025-04-22T02:54:08.306986+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\SyntaxError: "Unknown "app_navigation_data_links" function." at layout.html.twig line 96 {"exception":"[object] (Twig\\Error\\SyntaxError(code: 0): Unknown \"app_navigation_data_links\" function. at /var/www/html/templates/layout.html.twig:96)"} []
[2025-04-22T03:02:24.235861+00:00] security.ERROR: Detected CSRF attack on /admin/element/unlock-elements {"request":"/admin/element/unlock-elements"} []
[2025-04-22T03:02:24.238611+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" at CsrfProtectionHandler.php line 60 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Detected CSRF Attack! Do not do evil things with pimcore ... ;-) at /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Security/CsrfProtectionHandler.php:60)"} []
[2025-04-22T03:02:26.652368+00:00] security.ERROR: Detected CSRF attack on /admin/login/login {"request":"/admin/login/login"} []
[2025-04-22T03:02:26.660883+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" at CsrfProtectionHandler.php line 60 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Detected CSRF Attack! Do not do evil things with pimcore ... ;-) at /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Security/CsrfProtectionHandler.php:60)"} []
[2025-04-22T03:04:03.376881+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Call to undefined method image in class Pimcore\Model\DataObject\News")." at details.html.twig line 9 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Call to undefined method image in class Pimcore\\Model\\DataObject\\News\"). at /var/www/html/templates/news/details.html.twig:9)\n[previous exception] [object] (BadMethodCallException(code: 0): Call to undefined method image in class Pimcore\\Model\\DataObject\\News at /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php:226)"} []
[2025-04-22T03:05:05.603360+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Call to undefined method getImage in class Pimcore\Model\DataObject\News")." at details.html.twig line 9 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Call to undefined method getImage in class Pimcore\\Model\\DataObject\\News\"). at /var/www/html/templates/news/details.html.twig:9)\n[previous exception] [object] (BadMethodCallException(code: 0): Call to undefined method getImage in class Pimcore\\Model\\DataObject\\News at /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php:226)"} []
[2025-04-22T10:23:32.463376+00:00] console.CRITICAL: Error thrown while running command "messenger:consume pimcore_asset_update --memory-limit=250M --time-limit=3600". Message: "Could not connect to the AMQP server. Please verify the provided DSN." {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/AmqpReceiver.php:56)\n[previous exception] [object] (AMQPException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:491)\n[previous exception] [object] (AMQPConnectionException(code: 0): Socket error: could not connect to host, a socket error occurred at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:489)","command":"messenger:consume pimcore_asset_update --memory-limit=250M --time-limit=3600","message":"Could not connect to the AMQP server. Please verify the provided DSN."} []
[2025-04-22T10:23:32.463376+00:00] console.CRITICAL: Error thrown while running command "messenger:consume pimcore_core pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize --memory-limit=250M --time-limit=3600". Message: "Could not connect to the AMQP server. Please verify the provided DSN." {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/AmqpReceiver.php:56)\n[previous exception] [object] (AMQPException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:491)\n[previous exception] [object] (AMQPConnectionException(code: 0): Socket error: could not connect to host, a socket error occurred at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:489)","command":"messenger:consume pimcore_core pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize --memory-limit=250M --time-limit=3600","message":"Could not connect to the AMQP server. Please verify the provided DSN."} []
[2025-04-22T10:23:32.773434+00:00] console.CRITICAL: Error thrown while running command "messenger:consume pimcore_core pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize --memory-limit=250M --time-limit=3600". Message: "Could not connect to the AMQP server. Please verify the provided DSN." {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/AmqpReceiver.php:56)\n[previous exception] [object] (AMQPException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:491)\n[previous exception] [object] (AMQPConnectionException(code: 0): Socket error: could not connect to host, a socket error occurred at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:489)","command":"messenger:consume pimcore_core pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize --memory-limit=250M --time-limit=3600","message":"Could not connect to the AMQP server. Please verify the provided DSN."} []
[2025-04-22T10:23:33.031562+00:00] console.CRITICAL: Error thrown while running command "messenger:consume pimcore_asset_update --memory-limit=250M --time-limit=3600". Message: "Could not connect to the AMQP server. Please verify the provided DSN." {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/AmqpReceiver.php:56)\n[previous exception] [object] (AMQPException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:491)\n[previous exception] [object] (AMQPConnectionException(code: 0): Socket error: could not connect to host, a socket error occurred at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:489)","command":"messenger:consume pimcore_asset_update --memory-limit=250M --time-limit=3600","message":"Could not connect to the AMQP server. Please verify the provided DSN."} []
[2025-04-22T10:23:33.289488+00:00] console.CRITICAL: Error thrown while running command "messenger:consume pimcore_core pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize --memory-limit=250M --time-limit=3600". Message: "Could not connect to the AMQP server. Please verify the provided DSN." {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/AmqpReceiver.php:56)\n[previous exception] [object] (AMQPException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:491)\n[previous exception] [object] (AMQPConnectionException(code: 0): Socket error: could not connect to host, a socket error occurred at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:489)","command":"messenger:consume pimcore_core pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize --memory-limit=250M --time-limit=3600","message":"Could not connect to the AMQP server. Please verify the provided DSN."} []
[2025-04-22T10:23:33.552045+00:00] console.CRITICAL: Error thrown while running command "messenger:consume pimcore_asset_update --memory-limit=250M --time-limit=3600". Message: "Could not connect to the AMQP server. Please verify the provided DSN." {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/AmqpReceiver.php:56)\n[previous exception] [object] (AMQPException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:491)\n[previous exception] [object] (AMQPConnectionException(code: 0): Socket error: could not connect to host, a socket error occurred at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:489)","command":"messenger:consume pimcore_asset_update --memory-limit=250M --time-limit=3600","message":"Could not connect to the AMQP server. Please verify the provided DSN."} []
[2025-04-22T10:23:33.860097+00:00] console.CRITICAL: Error thrown while running command "messenger:consume pimcore_core pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize --memory-limit=250M --time-limit=3600". Message: "Could not connect to the AMQP server. Please verify the provided DSN." {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/AmqpReceiver.php:56)\n[previous exception] [object] (AMQPException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:491)\n[previous exception] [object] (AMQPConnectionException(code: 0): Socket error: could not connect to host, a socket error occurred at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:489)","command":"messenger:consume pimcore_core pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize --memory-limit=250M --time-limit=3600","message":"Could not connect to the AMQP server. Please verify the provided DSN."} []
[2025-04-22T10:23:34.203513+00:00] console.CRITICAL: Error thrown while running command "messenger:consume pimcore_asset_update --memory-limit=250M --time-limit=3600". Message: "Could not connect to the AMQP server. Please verify the provided DSN." {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/AmqpReceiver.php:56)\n[previous exception] [object] (AMQPException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:491)\n[previous exception] [object] (AMQPConnectionException(code: 0): Socket error: could not connect to host, a socket error occurred at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:489)","command":"messenger:consume pimcore_asset_update --memory-limit=250M --time-limit=3600","message":"Could not connect to the AMQP server. Please verify the provided DSN."} []
[2025-04-22T10:28:00.298267+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Call to undefined method image in class Pimcore\Model\DataObject\News")." at details.html.twig line 9 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Call to undefined method image in class Pimcore\\Model\\DataObject\\News\"). at /var/www/html/templates/news/details.html.twig:9)\n[previous exception] [object] (BadMethodCallException(code: 0): Call to undefined method image in class Pimcore\\Model\\DataObject\\News at /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php:226)"} []
[2025-04-22T10:35:41.706923+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Call to undefined method image in class Pimcore\Model\DataObject\News")." at details.html.twig line 9 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Call to undefined method image in class Pimcore\\Model\\DataObject\\News\"). at /var/www/html/templates/news/details.html.twig:9)\n[previous exception] [object] (BadMethodCallException(code: 0): Call to undefined method image in class Pimcore\\Model\\DataObject\\News at /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php:226)"} []
[2025-04-22T10:36:35.844082+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Call to undefined method image in class Pimcore\Model\DataObject\News")." at details.html.twig line 9 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Call to undefined method image in class Pimcore\\Model\\DataObject\\News\"). at /var/www/html/templates/news/details.html.twig:9)\n[previous exception] [object] (BadMethodCallException(code: 0): Call to undefined method image in class Pimcore\\Model\\DataObject\\News at /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php:226)"} []
[2025-04-22T10:37:24.626252+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "news/details.html.twig" (looked into: /var/www/html/templates)." at FilesystemLoader.php line 234 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Unable to find template \"news/details.html.twig\" (looked into: /var/www/html/templates). at /var/www/html/vendor/twig/twig/src/Loader/FilesystemLoader.php:234)"} []
[2025-04-22T10:44:25.958464+00:00] security.ERROR: Detected CSRF attack on /admin/element/unlock-elements {"request":"/admin/element/unlock-elements"} []
[2025-04-22T10:44:25.961723+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" at CsrfProtectionHandler.php line 60 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Detected CSRF Attack! Do not do evil things with pimcore ... ;-) at /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Security/CsrfProtectionHandler.php:60)"} []
[2025-04-22T10:51:01.384700+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\SyntaxError: "Unknown "app_navigation_data_links" function." at layout.html.twig line 97 {"exception":"[object] (Twig\\Error\\SyntaxError(code: 0): Unknown \"app_navigation_data_links\" function. at /var/www/html/templates/layout.html.twig:97)"} []
[2025-04-22T10:53:51.505994+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\SyntaxError: "Unknown "app_navigation_data_links" function." at layout.html.twig line 97 {"exception":"[object] (Twig\\Error\\SyntaxError(code: 0): Unknown \"app_navigation_data_links\" function. at /var/www/html/templates/layout.html.twig:97)"} []
[2025-04-22T14:08:48.748993+00:00] console.CRITICAL: Error thrown while running command "messenger:consume pimcore_core pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize --memory-limit=250M --time-limit=3600". Message: "Could not connect to the AMQP server. Please verify the provided DSN." {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/AmqpReceiver.php:56)\n[previous exception] [object] (AMQPException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:491)\n[previous exception] [object] (AMQPConnectionException(code: 0): Socket error: could not connect to host, a socket error occurred at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:489)","command":"messenger:consume pimcore_core pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize --memory-limit=250M --time-limit=3600","message":"Could not connect to the AMQP server. Please verify the provided DSN."} []
[2025-04-22T14:08:48.748993+00:00] console.CRITICAL: Error thrown while running command "messenger:consume pimcore_asset_update --memory-limit=250M --time-limit=3600". Message: "Could not connect to the AMQP server. Please verify the provided DSN." {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/AmqpReceiver.php:56)\n[previous exception] [object] (AMQPException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:491)\n[previous exception] [object] (AMQPConnectionException(code: 0): Socket error: could not connect to host, a socket error occurred at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:489)","command":"messenger:consume pimcore_asset_update --memory-limit=250M --time-limit=3600","message":"Could not connect to the AMQP server. Please verify the provided DSN."} []
[2025-04-22T14:08:49.045896+00:00] console.CRITICAL: Error thrown while running command "messenger:consume pimcore_asset_update --memory-limit=250M --time-limit=3600". Message: "Could not connect to the AMQP server. Please verify the provided DSN." {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/AmqpReceiver.php:56)\n[previous exception] [object] (AMQPException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:491)\n[previous exception] [object] (AMQPConnectionException(code: 0): Socket error: could not connect to host, a socket error occurred at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:489)","command":"messenger:consume pimcore_asset_update --memory-limit=250M --time-limit=3600","message":"Could not connect to the AMQP server. Please verify the provided DSN."} []
[2025-04-22T14:08:49.046749+00:00] console.CRITICAL: Error thrown while running command "messenger:consume pimcore_core pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize --memory-limit=250M --time-limit=3600". Message: "Could not connect to the AMQP server. Please verify the provided DSN." {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/AmqpReceiver.php:56)\n[previous exception] [object] (AMQPException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:491)\n[previous exception] [object] (AMQPConnectionException(code: 0): Socket error: could not connect to host, a socket error occurred at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:489)","command":"messenger:consume pimcore_core pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize --memory-limit=250M --time-limit=3600","message":"Could not connect to the AMQP server. Please verify the provided DSN."} []
[2025-04-22T14:08:49.323147+00:00] console.CRITICAL: Error thrown while running command "messenger:consume pimcore_asset_update --memory-limit=250M --time-limit=3600". Message: "Could not connect to the AMQP server. Please verify the provided DSN." {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/AmqpReceiver.php:56)\n[previous exception] [object] (AMQPException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:491)\n[previous exception] [object] (AMQPConnectionException(code: 0): Socket error: could not connect to host, a socket error occurred at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:489)","command":"messenger:consume pimcore_asset_update --memory-limit=250M --time-limit=3600","message":"Could not connect to the AMQP server. Please verify the provided DSN."} []
[2025-04-22T14:08:49.632145+00:00] console.CRITICAL: Error thrown while running command "messenger:consume pimcore_core pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize --memory-limit=250M --time-limit=3600". Message: "Could not connect to the AMQP server. Please verify the provided DSN." {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/AmqpReceiver.php:56)\n[previous exception] [object] (AMQPException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:491)\n[previous exception] [object] (AMQPConnectionException(code: 0): Socket error: could not connect to host, a socket error occurred at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:489)","command":"messenger:consume pimcore_core pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize --memory-limit=250M --time-limit=3600","message":"Could not connect to the AMQP server. Please verify the provided DSN."} []
[2025-04-22T14:08:49.923832+00:00] console.CRITICAL: Error thrown while running command "messenger:consume pimcore_asset_update --memory-limit=250M --time-limit=3600". Message: "Could not connect to the AMQP server. Please verify the provided DSN." {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/AmqpReceiver.php:56)\n[previous exception] [object] (AMQPException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:491)\n[previous exception] [object] (AMQPConnectionException(code: 0): Socket error: could not connect to host, a socket error occurred at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:489)","command":"messenger:consume pimcore_asset_update --memory-limit=250M --time-limit=3600","message":"Could not connect to the AMQP server. Please verify the provided DSN."} []
[2025-04-22T14:08:50.181595+00:00] console.CRITICAL: Error thrown while running command "messenger:consume pimcore_core pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize --memory-limit=250M --time-limit=3600". Message: "Could not connect to the AMQP server. Please verify the provided DSN." {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/AmqpReceiver.php:56)\n[previous exception] [object] (AMQPException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:491)\n[previous exception] [object] (AMQPConnectionException(code: 0): Socket error: could not connect to host, a socket error occurred at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:489)","command":"messenger:consume pimcore_core pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize --memory-limit=250M --time-limit=3600","message":"Could not connect to the AMQP server. Please verify the provided DSN."} []
[2025-04-22T14:08:50.450050+00:00] console.CRITICAL: Error thrown while running command "messenger:consume pimcore_asset_update --memory-limit=250M --time-limit=3600". Message: "Could not connect to the AMQP server. Please verify the provided DSN." {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/AmqpReceiver.php:56)\n[previous exception] [object] (AMQPException(code: 0): Could not connect to the AMQP server. Please verify the provided DSN. at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:491)\n[previous exception] [object] (AMQPConnectionException(code: 0): Socket error: could not connect to host, a socket error occurred at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:489)","command":"messenger:consume pimcore_asset_update --memory-limit=250M --time-limit=3600","message":"Could not connect to the AMQP server. Please verify the provided DSN."} []
[2025-04-22T14:26:08.407513+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Call to undefined method image in class Pimcore\Model\DataObject\News")." at detail.html.twig line 7 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Call to undefined method image in class Pimcore\\Model\\DataObject\\News\"). at /var/www/html/templates/news/detail.html.twig:7)\n[previous exception] [object] (BadMethodCallException(code: 0): Call to undefined method image in class Pimcore\\Model\\DataObject\\News at /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php:226)"} []
[2025-04-22T14:27:20.257001+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Call to undefined method getImage in class Pimcore\Model\DataObject\News")." at detail.html.twig line 7 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Call to undefined method getImage in class Pimcore\\Model\\DataObject\\News\"). at /var/www/html/templates/news/detail.html.twig:7)\n[previous exception] [object] (BadMethodCallException(code: 0): Call to undefined method getImage in class Pimcore\\Model\\DataObject\\News at /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php:226)"} []
[2025-04-22T14:28:40.940077+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Call to undefined method image in class Pimcore\Model\DataObject\News")." at detail.html.twig line 7 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Call to undefined method image in class Pimcore\\Model\\DataObject\\News\"). at /var/www/html/templates/news/detail.html.twig:7)\n[previous exception] [object] (BadMethodCallException(code: 0): Call to undefined method image in class Pimcore\\Model\\DataObject\\News at /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php:226)"} []
[2025-04-22T14:30:26.187171+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Call to undefined method getImage in class Pimcore\Model\DataObject\News")." at detail.html.twig line 7 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Call to undefined method getImage in class Pimcore\\Model\\DataObject\\News\"). at /var/www/html/templates/news/detail.html.twig:7)\n[previous exception] [object] (BadMethodCallException(code: 0): Call to undefined method getImage in class Pimcore\\Model\\DataObject\\News at /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php:226)"} []
[2025-04-22T14:38:29.140282+00:00] security.ERROR: Detected CSRF attack on /admin/element/unlock-elements {"request":"/admin/element/unlock-elements"} []
[2025-04-22T14:38:29.146623+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" at CsrfProtectionHandler.php line 60 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Detected CSRF Attack! Do not do evil things with pimcore ... ;-) at /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Security/CsrfProtectionHandler.php:60)"} []
[2025-04-22T14:38:32.421420+00:00] security.ERROR: Detected CSRF attack on /admin/login/login {"request":"/admin/login/login"} []
[2025-04-22T14:38:32.425669+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" at CsrfProtectionHandler.php line 60 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Detected CSRF Attack! Do not do evil things with pimcore ... ;-) at /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Security/CsrfProtectionHandler.php:60)"} []
[2025-04-22T19:05:45.089450+00:00] pimcore.ERROR: Class: DataObject\AbstractObject => call to undefined static method getBySlug [] []
[2025-04-22T19:05:45.089767+00:00] pimcore.ERROR: Class: DataObject\Concrete => call to undefined static method getBySlug [] []
[2025-04-22T19:05:45.092629+00:00] request.CRITICAL: Uncaught PHP Exception Exception: "Call to undefined static method getBySlug in class DataObject\Concrete" at Concrete.php line 616 {"exception":"[object] (Exception(code: 0): Call to undefined static method getBySlug in class DataObject\\Concrete at /var/www/html/vendor/pimcore/pimcore/models/DataObject/Concrete.php:616)"} []
[2025-04-22T19:06:41.321665+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Call to undefined method slug in class Pimcore\Model\DataObject\News")." at details.html.twig line 11 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Call to undefined method slug in class Pimcore\\Model\\DataObject\\News\"). at /var/www/html/templates/news/details.html.twig:11)\n[previous exception] [object] (BadMethodCallException(code: 0): Call to undefined method slug in class Pimcore\\Model\\DataObject\\News at /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php:226)"} []
[2025-04-22T19:07:38.344015+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Call to undefined method date in class Pimcore\Model\DataObject\News")." at details.html.twig line 23 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Call to undefined method date in class Pimcore\\Model\\DataObject\\News\"). at /var/www/html/templates/news/details.html.twig:23)\n[previous exception] [object] (BadMethodCallException(code: 0): Call to undefined method date in class Pimcore\\Model\\DataObject\\News at /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php:226)"} []
[2025-04-22T19:08:31.183443+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Call to undefined method image in class Pimcore\Model\DataObject\News")." at details.html.twig line 25 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Call to undefined method image in class Pimcore\\Model\\DataObject\\News\"). at /var/www/html/templates/news/details.html.twig:25)\n[previous exception] [object] (BadMethodCallException(code: 0): Call to undefined method image in class Pimcore\\Model\\DataObject\\News at /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php:226)"} []
[2025-04-22T19:11:32.127749+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Impossible to access an attribute ("id") on a null variable." at details.html.twig line 12 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Impossible to access an attribute (\"id\") on a null variable. at /var/www/html/templates/news/details.html.twig:12)"} []
[2025-04-22T19:24:35.130163+00:00] security.ERROR: Detected CSRF attack on /admin/element/unlock-elements {"request":"/admin/element/unlock-elements"} []
[2025-04-22T19:24:35.132652+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" at CsrfProtectionHandler.php line 60 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Detected CSRF Attack! Do not do evil things with pimcore ... ;-) at /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Security/CsrfProtectionHandler.php:60)"} []
[2025-04-22T19:29:08.947249+00:00] console.CRITICAL: Error thrown while running command "messenger:consume pimcore_core pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize --memory-limit=250M --time-limit=3600". Message: "Server channel error: 406, message: PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more" {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Server channel error: 406, message: PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more at /var/www/html/vendor/symfony/amqp-messenger/Transport/AmqpReceiver.php:56)\n[previous exception] [object] (AMQPQueueException(code: 406): Server channel error: 406, message: PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more at /var/www/html/vendor/symfony/amqp-messenger/Transport/Connection.php:432)","command":"messenger:consume pimcore_core pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize --memory-limit=250M --time-limit=3600","message":"Server channel error: 406, message: PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more"} []
[2025-04-22T19:29:08.960511+00:00] php.CRITICAL: Uncaught Exception: The acknowledger was not called by the "Pimcore\Messenger\Handler\SanityCheckHandler" batch handler. {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\LogicException(code: 0): The acknowledger was not called by the \"Pimcore\\Messenger\\Handler\\SanityCheckHandler\" batch handler. at /var/www/html/vendor/symfony/messenger/Handler/Acknowledger.php:66)"} []
[2025-04-22T19:29:08.962109+00:00] php.CRITICAL: Uncaught Exception: The acknowledger was not called by the "Pimcore\Messenger\Handler\SanityCheckHandler" batch handler. {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\LogicException(code: 0): The acknowledger was not called by the \"Pimcore\\Messenger\\Handler\\SanityCheckHandler\" batch handler. at /var/www/html/vendor/symfony/messenger/Handler/Acknowledger.php:66)"} []
[2025-04-22T19:29:08.989304+00:00] php.CRITICAL: Uncaught Exception: The acknowledger was not called by the "Pimcore\Messenger\Handler\SanityCheckHandler" batch handler. {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\LogicException(code: 0): The acknowledger was not called by the \"Pimcore\\Messenger\\Handler\\SanityCheckHandler\" batch handler. at /var/www/html/vendor/symfony/messenger/Handler/Acknowledger.php:66)"} []
[2025-04-22T19:34:50.879019+00:00] security.ERROR: Detected CSRF attack on /admin/page/save {"request":"/admin/page/save"} []
[2025-04-22T19:34:50.882379+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" at CsrfProtectionHandler.php line 60 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Detected CSRF Attack! Do not do evil things with pimcore ... ;-) at /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Security/CsrfProtectionHandler.php:60)"} []
[2025-04-22T19:47:40.518656+00:00] security.ERROR: Detected CSRF attack on /admin/element/unlock-elements {"request":"/admin/element/unlock-elements"} []
[2025-04-22T19:47:40.521018+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" at CsrfProtectionHandler.php line 60 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Detected CSRF Attack! Do not do evil things with pimcore ... ;-) at /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Security/CsrfProtectionHandler.php:60)"} []
[2025-04-22T20:18:34.718567+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\SyntaxError: "Unknown "app_navigation_data_links" function." at layout.html.twig line 102 {"exception":"[object] (Twig\\Error\\SyntaxError(code: 0): Unknown \"app_navigation_data_links\" function. at /var/www/html/templates/layout.html.twig:102)"} []
[2025-04-22T20:42:33.619107+00:00] security.ERROR: Detected CSRF attack on /admin/element/unlock-elements {"request":"/admin/element/unlock-elements"} []
[2025-04-22T20:42:33.622419+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" at CsrfProtectionHandler.php line 60 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Detected CSRF Attack! Do not do evil things with pimcore ... ;-) at /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Security/CsrfProtectionHandler.php:60)"} []
[2025-04-22T21:08:08.716825+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "media" does not exist." at view.html.twig line 110 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"media\" does not exist. at /var/www/html/templates/areas/text-with-image/view.html.twig:110)"} []
[2025-04-22T21:08:16.721373+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "media" does not exist." at view.html.twig line 110 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"media\" does not exist. at /var/www/html/templates/areas/text-with-image/view.html.twig:110)"} []
[2025-04-22T21:08:27.163570+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "media" does not exist." at view.html.twig line 110 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"media\" does not exist. at /var/www/html/templates/areas/text-with-image/view.html.twig:110)"} []
